<?php

/**
   * {@inheritdoc}
   */
/**
   * A simple hook form alter to customize the form with siteapikey textfield and making custom submit form
   */
    function node_to_json_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
        $site_apikey_setting	= \Drupal::config('system.site')->get('siteapikey')?\Drupal::config('system.site')->get('siteapikey'):t('No API Key yet');
        if(in_array("administrator", \Drupal::currentUser()->getRoles())) {
                $form['site_information']['siteapikey'] = [
                    '#type' => 'textfield',
                    '#title' => t('Site API Key'),
                    '#description' => t('Please Enter 16 character to access some pages of this site.'),
                    '#default_value' => $site_apikey_setting,
                    '#weight' => '2',
                ];
                if(\Drupal::config('system.site')->get('siteapikey') != t('No API Key yet')) {
                    $form['actions']['submit']['#value'] = 'Update Configuration';   
                }			
                //Customizing the form submit
                $form['#submit'][] = 'Drupal\node_to_json\Controller\NodeToJsonController::site_apikey_form_submit';			
        }	
    }